export const PERSONAS = [
  { id: "cmo", label: "CMO", shortDesc: "Vision, budget, business outcomes", desc: "Faces unrelenting pressure to deliver more with fewer resources. Battles fragmented tech, siloed teams, and organizational chaos that hold marketing back. Needs content at unprecedented scale to meet customer demand for hyper-personalization — but creative teams are stretched thin and burnout is rising. Evaluates tools on whether they drive business growth, unlock high-performing creative at unmatched scale and speed, and help marketing prove its value to the board." },
  { id: "marketing-dm", label: "Marketing DM", shortDesc: "Execution, campaign performance", desc: "Brings CMO vision to life through campaign execution, performance metrics, and team output. Battles tech silos, slow approvals, and manual workflows that slow execution and kill ROI. Expected to execute across fragmented tools, channels, and audiences while resources shrink and expectations rise. Evaluates tools on whether they deliver real-time performance insights, remove creative bottlenecks, and enable hyper-personalized experiences at scale." },
  { id: "creative-dm", label: "Creative DM", shortDesc: "Brand, creative excellence", desc: "Leads creative excellence and brand integrity while facing skyrocketing content demand with fewer resources. Worries about AI making everything look the same. Needs to deliver standout, on-brand content across more channels, faster than ever — without burning out the team. Evaluates tools on whether they free creatives from the mundane, unlock data-driven creativity, and protect brand consistency at scale without sacrificing creative quality." },
  { id: "cio", label: "CIO", shortDesc: "Digital transformation, AI strategy", desc: "Increasingly tasked with setting business strategy and owning outcomes beyond IT. Battles fragmented technology, siloed teams, legacy systems, and a workforce unprepared for AI. Cares deeply about security, governance, responsible AI, and reducing vendor sprawl. Evaluates tools on whether they modernize the tech stack, consolidate point solutions into a unified platform, and deliver trusted, enterprise-grade AI with accountability and transparency at the core." },
  { id: "it-dm", label: "IT DM", shortDesc: "Integration, security, vendor eval", desc: "Executes the CIO's strategy and manages the day-to-day reality of disparate, outdated tech stacks that stifle innovation and burden IT with costly maintenance. Faces mounting pressure to prove ROI, cut costs, and scale efficiently. Cares about security, compliance, system performance, and upskilling the workforce for new ways of working. Evaluates tools on integration reliability, responsible AI governance, and whether they reduce vendor sprawl and streamline IT maintenance." },
  { id: "martech-dm", label: "MarTech / Ops DM", shortDesc: "Stack, campaign ops, data", desc: "Bridges CMO vision and CIO strategy through technical campaign execution and MarTech stack management. Battles tech silos, slow approvals, dated tools, and manual workflows that stall delivery and kill ROI. Must orchestrate campaigns across fragmented tools and channels while budgets shrink and customer demand for hyper-personalized omnichannel experiences soars. Evaluates tools on whether they unify workflows, integrate cleanly, enable AI-driven decision making, and reduce operational friction without burning out the team." },
];

export const STAGES = [
  { id: "discovery", label: "Discovery", desc: "Something feels broken but they cannot name the problem yet — describing symptoms" },
  { id: "exploration", label: "Exploration", desc: "Understands the problem clearly and is actively looking for approaches and solutions" },
  { id: "evaluation", label: "Evaluation", desc: "Knows what kind of solution they need and is comparing vendors and building a shortlist" },
  { id: "decision", label: "Decision", desc: "Close to choosing, looking for reassurance, pricing, case studies, or negotiation leverage" },
];
